### ISSUE TITLE
Bug with LegendBox

### ISSUE THREAD

**Issue by protik77** [masumhabib/PlotPub#5] opened 2015-03-31 00:13 UTC
I tried the code below with LegendBox 'on'

```
clear all;

f = 50;  % frequency
Vm = 10; % peak
phi = 0; % phase
 
% generate the signal
t = [0:0.0001:3/f];
th = 2*pi*f*t;
v = Vm*sin(th+phi);

figure;
plot(t*1E3, v);

plt = Plot();

plt.Legend={'some'};
plt.LegendBox='on';
```

Here the LegendBox interferes with the curve of the graph. I think it shouldn't. So for a workaround I added the line below.

```
plt.BoxDim=[6 5];
```
Now the upper portion of the figure goes outside of the monitor. So I had to reduce the size of the figure to get a hold. I tried this both with windows 7 & 8.1.

**Comment by masumhabib** [comment] 2015-03-31 01:59
Protik,

Thanks for the bug report. By default the LegendBoxColor was 'none'; meaning, it was transparent. That is why the curve was visible. Now I changed it to white. Please download the development branch to test this. I'll merge the change to master in the next release.

As for the BoxDim problem, I could not reproduce on my Mac. Does it happen in a single monitor system or in a multi monitor system? Which version of MATLAB are you using?

**Comment by protik77** [comment] 2015-04-06 03:14
The box is now white. But the legend box is still overlapping with the original curve. Can you set this up in a way so that the legend box stays out of the curve in the figure? Then one doesn't need to manually change the dimension of the box.
![test](https://cloud.githubusercontent.com/assets/1991215/7000081/fc2f0890-dbce-11e4-9c10-5a934fe6d9bc.jpg)

For the BoxDim problem I tried it for both single monitor & multi-monitor system in windows 8. It's not that much of a problem in 8. Because even when the top of the image with menus like minimize, maximize or close button is outside, if you hover over the top of the image, whole figure comes down a little bit & the menus become visible. 
![screenshot 2015-04-05 20 07 52](https://cloud.githubusercontent.com/assets/1991215/7000109/88b75010-dbcf-11e4-8ad6-0bd22126d40f.png)

But for windows 7 it doesn't do that. I tested for  multi-monitor system. I'll test it for single monitor system & let you know. It seems if the BoxDim is changed, the lower left corner of the figure is fixed & Matlab increases the frame to the right & top. That's why this problem is occuring.

**Comment by protik77** [comment] 2015-04-06 03:15
The box is now white. But the legend box is still overlapping with the original curve. Can you set this up in a way so that the legend box stays out of the curve in the figure? Then one doesn't need to manually change the dimension of the box.
![test](https://cloud.githubusercontent.com/assets/1991215/7000081/fc2f0890-dbce-11e4-9c10-5a934fe6d9bc.jpg)

For the BoxDim problem I tried it for both single monitor & multi-monitor system in windows 8. It's not that much of a problem in 8. Because even when the top of the image with menus like minimize, maximize or close button is outside, if you hover over the top of the image, whole figure comes down a little bit & the menus become visible. 
![screenshot 2015-04-05 20 07 52](https://cloud.githubusercontent.com/assets/1991215/7000109/88b75010-dbcf-11e4-8ad6-0bd22126d40f.png)

But for windows 7 it doesn't do that. I tested for  multi-monitor system. I'll test it for single monitor system & let you know. It seems if the BoxDim is changed, the lower left corner of the figure is fixed & Matlab increases the frame to the right & top. That's why this problem is occuring.

**Comment by masumhabib** [comment] 2015-04-06 23:00
Now I see what you are asking. One way to get a non-overlapping legend is to increase the XLim from 60. Try this in your plot:
```matlab
plt.XLim = [0, 80];
```

**Comment by masumhabib** [comment] 2015-04-06 23:03
Please let me know if the window problem happens in single monitor too.

**Comment by protik77** [comment] 2015-04-08 03:38
Okay, I tested it for both single & multi-monitor system. I also figured out why it happens. It seems it's a common problem with Matlab in windows 7 OS. By following this link (http://www.mathworks.com/matlabcentral/answers/101277-is-it-possible-to-force-matlab-to-bring-up-figure-windows-on-the-primary-monitor-or-in-a-specific-po) I found that there is a default value for mouse position. In my case it was in the middle of the monitor. So when I increased the dimension of the box, it expanded the figure from there. 

There are two possible workaround for this. One is to change the default position globally (`FactoryFigurePosition`) or setting it for current session (`DefaultFigurePosition`) while the Plot() is called. I guess it will be better if it's for only current session.

**Comment by masumhabib** [comment] 2015-04-08 13:03
So, does this happen both in single-monitor and in multi-monitor?

**Comment by masumhabib** [comment] 2015-04-08 13:41
Thanks for the information. It was very useful.

I think, I fixed it. Since I do not have a windows machine, I cannot test. Could you download the hotfix-5 branch and test it in both single-monitor and in multi-monitor?

**Comment by protik77** [comment] 2015-04-10 19:21
In my windows 7 it's like this:
![plotbug2](https://cloud.githubusercontent.com/assets/1991215/7094679/5559e640-df78-11e4-9ffe-f6139858ca26.PNG)

I tried the same in my windows 8. It's like below.

![screenshot 2015-04-10 11 57 23](https://cloud.githubusercontent.com/assets/1991215/7094858/19c13834-df7a-11e4-868d-c695960dad5d.png)

The scenarios are same for both single & multi monitor system. For multi monitor system it occurs at the primary monitor. It seems you need to figure out the pixel dimension of the monitor & put some intelligent ratio for positioning the image. For you convenience I'm giving some coordinates while positioning the figure at different positionas. I ran `p=get(gcf, 'Position')`.

In my desktop having windows 7 the value for bottom left corner is `(5, 48)`, top left corner `(5, 511)`, top right corner `(238, 284)`, bottom right corner `(707, 47)`.

In my laptop having windows 8 the value for bottom left corner is `(8, 47)`, top left corner `(7, 264)`, top right corner `(803, 264)`, bottom right corner `(802, 46)`.

**Comment by masumhabib** [comment] 2015-04-10 21:06
Very weird. The code actually gets the monitor size and try to put the figure at the middle of the monitor. Win7 is messed up.

Can you post the output of the following both for Win7 and for Win8?
```matlab
set(0, 'Units', 'inch');                                            
monitorPos = get(0,'MonitorPositions')
```

**Comment by protik77** [comment] 2015-04-10 21:21
For win7:
```
monitorPos =

   13.3333         0   13.3333   10.6667
         0         0   13.3333   10.6667
```

For Win8
```
monitorPos =
 
         0         0   14.2292    8.0000
         0    8.0000   13.3333   10.6667
```

**Comment by masumhabib** [comment] 2015-04-15 02:27
Really weird. Is it showing two monitors?

**Comment by masumhabib** [comment] 2015-04-15 02:40
I changed the code based on the monitorPos. Could you check the hotfix-5 branch one more time?

**Comment by protik77** [comment] 2015-04-15 20:52
Now working perfect. Tested both with single & multi-monitor system with Windows 7 OS.

**Comment by masumhabib** [comment] 2015-04-16 02:13
Would you also test in Win8?

**Comment by protik77** [comment] 2015-04-16 03:38
Tested for both single & multi-monitor system with Win8. Works great.

Now you can only cause the problem if the BoxDim is too high like `[6 5]`. I don't think one needs this big figure.

**Comment by masumhabib** [comment] 2015-04-16 18:34
Thanks Protik. The fix is now merged to develop branch and will be available in master in the next release.

**Closed by masumhabib** 2015-04-16 18:34 UTC
